version: "3.0"
services:
  app:
    build:
      context: .
    links:
      - database
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
      - "MAIL_PORT=1025"
  database:
    build:
      context: .
      dockerfile: Dockerfile.sql
    environment:
      - "MYSQL_DATABASE=example"
      - "MYSQL_PASSWORD=example"
      - "MYSQL_ROOT_PASSWORD=example"
